title: "Bug Bounty Writeups"
description: "Writeups, techniques, and bug bounty knowledge by Akash Hamal (@akashhamal0x01)"
author: Akash Hamal
url: "https://akashhamal0x01.me"
baseurl: ""
theme: null
plugins:
  - jekyll-feed
