title: "Bug Bounty Writeups"
author: Akash Hamal
description: Writeups, techniques, and bug bounty knowledge by @akashhamal0x01
baseurl: ""
url: "https://akashhamal0x01.me"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
